{{- if .Values.ingress.enabled }}
{{- $fullName := include "prometheus-pushproxy.fullname" . }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "prometheus-pushproxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prometheus-pushproxy.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /healthz
            backend:
              serviceName: {{ include "prometheus-pushproxy.fullname" . }}
              servicePort: {{ .Values.config.port }}
          - path: /v1
            backend:
              serviceName: {{ include "prometheus-pushproxy.fullname" . }}
              servicePort: {{ .Values.config.port }}
          - path: /proxy-metrics
            backend:
              serviceName: {{ include "prometheus-pushproxy.fullname" . }}
              servicePort: {{ .Values.config.port }}
{{- end }}
